import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { Layout } from "@/components";
import { CartProvider } from "@/context/CartProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Layout>
            <Toaster />
            {children}
          </Layout>
        </CartProvider>
      </body>
    </html>
  );
}
